### ISSUE TITLE
Avoid n/a values for current day min/max temperatures?

### ISSUE THREAD

**Issue by nickdos** [bremor/bom_forecast#21]
The current day forecast (rest of the day, I suppose) is showing both min and max temperatures as `n/a`, which looks a bit broken on the friendly card. See:

<img width="373" alt="image" src="https://user-images.githubusercontent.com/532845/61771881-3f987800-ae34-11e9-8593-f9e0b2530934.png">

Ideally, the values forecasted for the current day should remain but I'm guessing BOM is not sending them through in the feed. 

I tried using template expressions (to try to check for `n/a` and then output nothing) but they came out as literal characters. 

Any suggestions for avoiding the `n/a` values?

**Comment by nickdos** [comment]
Answering my own question. I worked out a template sensor can do this:

```yaml
sensor:
  - platform: template
    sensors:
      bom_current_day_forecast:
         value_template: '{{ states.sensor.bom_forecast_canberra_0.attributes.Summary }}'  
         friendly_name: 'Today' 
         icon_template: '{{ states.sensor.bom_forecast_canberra_0.attributes.icon }}'
```

I tried using a template for the `friendly_name` but it came out as `{{states.sensor.bom_forecast_canberra_0.attributes. friendly_name }}`, so went with `today` instead.
